---

- name: Check n is already installed.
  shell: which n
  register: n_is_installed
  changed_when: false
  failed_when: n_is_installed.rc not in [0, 1]

- name: Install Node.js
  apt:
    name: [ nodejs, npm ]
  when: n_is_installed.rc == 1

- name: Install version manager for node
  npm:
    name: n
    global: yes
  when: n_is_installed.rc == 1

- name: Install stable node.
  shell: n stable
  when: n_is_installed.rc == 1
 
- name: Purge Node.js
  apt:
    name: nodejs
    state: absent
    purge: yes
  when: n_is_installed.rc == 1